dsps/diffstar_photometry.py, dsps/diffstar_photometry_kernels.py, dsps/load_diffstar_data.py, dsps/tests/test_diffstar_photometry_kernels.py
PR brings in code implementing age-dependent models of attentuation
=> Age dep attenuation

README.md
README now links to dsps.readthedocs.io
=> Update readme with link to rtd

dsps/imf/remnant_mass.py, dsps/imf/surviving_mstar.py, dsps/metallicity/mzr.py, dsps/metallicity/tests/test_mzr.py, dsps/utils.py
This PR removes some functions in `mzr.py` made obsolete by #30
=> Clean up mzr module

dsps/tests/test_utils.py, dsps/utils.py
Common utility function for parameter bounding is now in dsps.utils
=> Add _inverse_sigmoid function to utils.py

dsps/cosmology/flat_wcdm.py, dsps/cosmology/tests/test_flat_wcdm.py, dsps/metallicity/tests/test_mzr.py, dsps/photometry/photometry_kernels.py, dsps/photometry/photpop.py, dsps/photometry/tests/test_photometry_kernels.py, dsps/photometry/tests/test_photpop.py
This PR refactors all the kernels located in dsps/cosmology. Many functions have been renamed, and the number of flat w0/wa CDM parameters has been reduced from 5 to 4, so this is an API-breaking PR.
=> Refactor cosmology subdirectory

dsps/sed/csp_sed.py, dsps/sed/metallicity_weights.py, dsps/sed/ssp_weights.py, dsps/sed/stellar_age_weights.py, dsps/sed/tests/test_csp_sed.py, dsps/sed/tests/test_metallicity_weights.py, dsps/sed/tests/test_ssp_weights.py
This PR refactors all the kernels located in dsps/sed. Many functions have been renamed, so this is an API-breaking PR.
=> Update API and docstrings of sed subdirectory

dsps/photometry/photometry_kernels.py, dsps/photometry/photpop.py, dsps/photometry/tests/test_photometry_kernels.py
This PR renames a few of the kernels located in dsps/photometry, so this is an API-breaking PR.
=> Update API of photometry_kernels module

.github/workflows/codecov.yml, .github/workflows/tests.yml
=> Add codecov github action

docs/source/dsps_quickstart.ipynb, dsps/cosmology/__init__.py, dsps/cosmology/defaults.py, dsps/cosmology/flat_wcdm.py, dsps/cosmology/tests/test_flat_wcdm.py, dsps/photometry/__init__.py, dsps/photometry/photometry_kernels.py
This PR updates the quickstart guide with a demonstration of photometry calculations
=> Add photometry demo to quickstart guide

docs/source/index.rst, docs/source/reference.rst
Add API Reference section to docs
=> Add API Reference section to docs

dsps/sed/__init__.py, dsps/sed/metallicity_weights.py, dsps/sed/ssp_weights.py, dsps/sed/stellar_age_weights.py
Add sed kernels to top-level dsps imports
=> Add sed kernels to top-level dsps imports

docs/source/custom_ssps.rst, docs/source/quickstart.rst
This could use a little more flesh and maybe a worked example in a future PR.
=> New page in docs on using alternative SSP libraries

dsps/tests/test_utils.py, dsps/utils.py
This PR adds a differentiable Monte Carlo realization of a powerlaw to dsps.utils
=> Add powerlaw_rvs to dsps.utils

docs/source/custom_ssps.rst, docs/source/dsps_data_config.rst, docs/source/quickstart.rst, dsps/data/README.txt
Improve documentation on data loading
=> Improve documentation on data loading

.git_archival.txt, .gitattributes
This PR fixes a versioning bug pointed out by @beckermr
=> Add git_archival.txt and gitattributes so that setuptools_scm works

README.md
One less thing to have to change with releases
=> Only state major version in readme

dsps/data_loaders/retrieve_fsps_data.py
PR adds option to pass on keyword arguments to FSPS from the retrieve_ssp_data_from_fsps function
=> Add optional keyword arguments to retrieve_ssp_data_from_fsps

dsps/dust/__init__.py, dsps/dust/blackbody.py, dsps/dust/tests/test_blackbody.py
PR brings in a JAX implementation of a blackbody spectrum. Unit tests enforce agreement with astropy.
=> Add blackbody SED module

dsps/data_loaders/retrieve_fsps_data.py
Catch exception accidentally leading to FSPS installation requirement
CC @torluca
=> Bug fix related to FSPS import

.github/workflows/linting.yml, .github/workflows/tests.yml
=> Cron tests

pyproject.toml
infer dependencies from requirements.txt from within pyprojec.toml
=> infer dependencies from requirements.txt from within pyprojec.toml

.github/workflows/tests.yml
=> Add test of versioning

.github/workflows/monthly-warning-test.yml
- Runs on the 1st of every month
- Also runs on pull request (at least for now so we can see it in action)
=> Monthly cron that raises errors if there are any warnings

.github/workflows/monthly-warning-test.yml, dsps/cosmology/flat_wcdm.py, dsps/dust/utils.py, dsps/em_lines/equivalent_width.py, dsps/photometry/photometry_kernels.py, dsps/tests/test_utils.py, dsps/utils.py
Add trapz kernel and switch to PR testing for warnings
=> Add trapz kernel and switch to PR testing for warnings

dsps/utils.py
jax.lax.logistic-->jax.nn.sigmoid
=> jax.lax.logistic-->jax.nn.sigmoid

.github/workflows/linting.yml, .github/workflows/monthly-warning-test.yml, .github/workflows/tests.yml
Switch to python 3.11 testing env
=> Switch to python 3.11 testing env

dsps/metallicity/tests/test_umzr.py, dsps/metallicity/umzr.py
Fix bug in unbounding function of mass-metallicity relation parameter
=> Fix bug in unbounding function of mass-metallicity relation parameter

.github/workflows/monthly-warning-test.yaml, .github/workflows/tests.yaml, dsps/metallicity/diagnostics/plot_mzr.py, dsps/metallicity/diagnostics/tests/test_plot_mzr.py, dsps/metallicity/tests/testing_data/README.txt
This PR brings in a wrapper function that produces this plot
=> Add diagnostic plotting for MZR

dsps/photometry/photometry_kernels.py, dsps/photometry/photpop.py, dsps/photometry/tests/test_photometry_kernels.py, dsps/photometry/tests/test_photpop.py, dsps/photometry/utils.py
Add `precompute_ssp_restmags_z_kcorrect` convenience function
=> Add `precompute_ssp_restmags_z_kcorrect` convenience function

dsps/cosmology/flat_wcdm.py, dsps/cosmology/tests/test_flat_wcdm.py
Add calculation of differential_comoving_volume. Also include new function `comoving_distance`, which is a vmapped version of `comoving_distance_to_z`.
=> Add calculation of differential_comoving_volume

CHANGES.rst
=> Update changelog for `v0.4.3`
