- dsps/mzr.py
- dsps/stellar_ages.py
- dsps/utils.py
This PR replaces the deprecated use of jax.ops.index_update with the new preferred syntax
> Use new jax syntax for array index updates

- dsps/attenuation_kernels.py
- dsps/tests/test_attenuation.py
- dsps/utils.py
New **triweight_k_lambda** function approximates the Noll+09 attenuation curve, but has better asymptotic behavior when extrapolating beyond the range where the Noll+09 curves were calibrated.
The attenuation curve `A(λ)` defines a multiplier `F_att(λ)` of the intrinsic flux `L_true(λ)` to produce the observed flux: 
$$A(\lambda) = A_{V}\cdot k_{\lambda}$$
$$F_{\rm att}(\lambda) = 10^{-0.4\cdot A(\lambda)}$$
$$L_{\rm obs}(\lambda)=F_{\rm att}(\lambda)\cdot L_{\rm true}(\lambda)$$
Many common attenuation curves are defined in terms of the [Calzetti](https://github.com/ArgonneCPAC/dsps/blob/9a80fdc89944786ae11e8d63ee13caa91e207895/dsps/attenuation_kernels.py#L50) `k_lambda` function, which is a polynomial function of 1/λ that blows up at short wavelengths. There are other forms implemented …
> NaN-safe k_ λ attenuation curve

- dsps/attenuation_kernels.py
Add optional argument to _flux_ratio function to support [Lower+22](https://arxiv.org/abs/2203.00074) attenuation
> Add support for Lower+22 attenuation curve flexibility

- dsps/ssp/diffburst.py
- dsps/ssp/tests/test_diffburst.py
This PR brings in the Diffburst model of a PDF of stellar ages for a very young population. Diffburst is a two-parameter family for P(τ_age) based on a triweight function. The first parameter, τ_burst, controls the timescale of the burst - smaller values of τ_burst produce younger stellar populations. The second parameter, F_burst, controls the normalization of the burst, defined as a fraction of the total mass formed at z_obs.
The plot below compares the τ_age PDF of a pure burst to a typical main sequence Diffstar galaxy.
This next plot shows how the composite τ_age PDF looks for a few different variations in F_burst and τ_burst.
This last plot shows how the pure-burst SED compares to the Diffstar SED, as well as a couple of composite spectra.
> Add diffburst module

- dsps/tests/test_utils.py
- dsps/utils.py
This PR brings in a couple of convenience functions to utils.py that are commonly used when calculating the PDF-weighting of the SSPs.
> Add kernels for 2d and 3d weight matrices per galaxy to utils.py

- requirements.txt
- setup.py
DSPS source code no longer uses these. This PR just removes them from `requirements.txt` and `setup.py`
> Remove dependencies on diffmah and diffstar

- dsps/constants.py
- dsps/csp_seds/composite_sed.py
- dsps/csp_seds/metallicity_weights.py
- dsps/csp_seds/ssp_weights.py
- dsps/csp_seds/stellar_age_weights.py
- dsps/csp_seds/tests/test_composite_sed.py
- dsps/csp_seds/tests/test_metallicity_weights.py
- dsps/csp_seds/tests/test_ssp_weights.py
- dsps/csp_seds/tests/test_stellar_age_weights.py
This PR collects many of the PDF-weighted summation kernels into a new `csp_seds` subdirectory. Kernels in this directory will ultimately replace many of the functions currently located elsewhere in DSPS, and so this PR is part of a series of API-breaking changes that will comprise the next release. 
@suchethac the `csp_seds` subdirectory includes new kernels for calculating metallicity weights and SEDs based on an input tabulation of the metallicity history of a galaxy.
> Bring in csp_seds subdirectory for core kernels of SED calculations

- dsps/sed/stellar_age_weights.py
- dsps/sed/tests/test_stellar_age_weights.py
This PR changes the API of `_calc_age_weights_from_logsm_table`, an internal function called by `_calc_age_weights_from_sfh_table`. The `_calc_age_weights_from_sfh_table` accepts an input linear time argument in log-space, and it computes log10(time) within its namespace, since this function requires both logspace and linear space time computations. But the `_calc_age_weights_from_sfh_table` now accepts log10(t), since all this function does is interpolate log10(t) against logsm. It's a reasonably common use-case to call `_calc_age_weights_from_logsm_table` directly, and so this internal API change now means users don't have to take an extra logarithm if they have computed it already. But this PR leaves the behavior of `_calc_age_weights_from_sfh_table` unchanged.
> Refactor internals in stellar age weight calculations

- dsps/dust/attenuation_kernels.py
- dsps/dust/tests/test_attenuation.py
This PR builds on #20 by exposing the Lower+2022 unobscured fraction feature to the `_get_effective_attenuation` function. The plot below illustrates the character of the DoF of the unobscured fraction on the attenuation fraction.
> Add support for Lower+22 unobscured fractions in effective attenuation curves

- docs/source/conf.py
Was previously hard-coded to `"0.2.0"`. Now version is inferred using `pkg_resources.get_distribution`
> Fix hard-coded version in conf.py

- .gitignore
- dsps/__init__.py
- dsps/data_loaders/__init__.py
- dsps/data_loaders/defaults.py
- dsps/data_loaders/load_filter_data.py
- dsps/data_loaders/load_ssp_data.py
- dsps/data_loaders/tests/test_load_filter_data.py
New load_filter_data.py module reads transmission curves stored to disk, optionally searching DSPS_DRN as the default location
> Add load_filter_data.py module to data_loaders

- docs/source/dsps_quickstart.ipynb
- dsps/constants.py
- dsps/cosmology/__init__.py
- dsps/cosmology/defaults.py
- dsps/cosmology/flat_wcdm.py
- dsps/cosmology/tests/test_flat_wcdm.py
- dsps/sed/stellar_age_weights.py
This PR brings in a new function `cosmology.flat_wcdm.age_at_z`, and removes the previously hard-coded value of dsps.TODAY.
Resolves #50.
> Add calculator of age of the universe at z

- .github/workflows/publish-to-pypi.yml
Add publish-to-pypi.yml workflow. This was copied from an example project created with [the LINCC framework](https://github.com/lincc-frameworks/python-project-template), and a repository secret for pypi has now been added following the instructions in [the PyPi section of the LINCC docs](https://lincc-ppt.readthedocs.io/en/latest/practices/pypi.html). Thanks to @drewoldag and @eacharles for pointing me to this very useful workflow.
> Add publish-to-pypi.yml workflow

- dsps/metallicity/mzr.py
- dsps/metallicity/tests/test_mzr.py
This PR changes the mzr module to observe the convention used elsewhere that parameter _dictionaries_ have global names concluding with PDICT while parameter _arrays_ conclude with PARAMS
> Change mzr.DEFAULT_MZR_PARMAS to mzr.DEFAULT_MZR_PDICT

- dsps/data_loaders/retrieve_fake_fsps_data.py
This PR removes a forgotten/unintentional import from scipy rather than jax.scipy identified by [this PR in the dsps-feedstock](https://github.com/conda-forge/dsps-feedstock/pull/6)
CC @beckermr
> Import scipy.stats.norm from jax rather than scipy

- dsps/cosmology/flat_wcdm.py
- dsps/dust/blackbody.py
- dsps/tests/test_utils.py
- dsps/utils.py
This PR improves numerical robustness of the calls to the exponential function, resolving an issue leading to NaNs in gradients.
> Replace jnp.exp --> lax.exp

- dsps/__init__.py
- dsps/constants.py
- dsps/tests/test_utils.py
- dsps/utils.py
This PR brings in a new kernel, `dsps.utils.cumulative_mstar_formed`, that computes the cumulative stellar mass formed from an input SFH table. A few notes:
* Trapezoidal integration is used to integrate an input `sfh_table` across an input `t_table` under the assumption that SFR=SFR_MIN during the interval `dsps.constants.T_BIRTH_MIN < t < t_table[0]`.
* The implementation requires that `t_table[0] >= dsps.constants.T_TABLE_MIN`.
* Note that `T_BIRTH_MIN=0.001 Gyr` corresponds to `z~600`, `T_TABLE_MIN=0.01 Gyr` corresponds to `z~140`, and `SFR_MIN=1e-14`, so these boundary conditions should not impact galaxy mass at any redshift of practical interest.
Cumulative trapezoidal integration is not implemented in `jax.numpy`, and so this PR brings in a new custom kernel for this computation, …
> Add cumulative_mstar_formed function to dsps.utils

- dsps/metallicity/mzr.py
Change normalization convention of the mzr relation so that the mzr_model function now returns metallicity rather Z/Zsun
> mzr model now return absolute metallicity rather than Z/Zsun

- dsps/sed/stellar_age_weights.py
- dsps/sed/tests/test_csp_sed.py
- dsps/sed/tests/test_ssp_weights.py
Trapezoidal integration of stellar age weights
> Trapezoidal integration of stellar age weights

- dsps/sfh/diffburst.py
- dsps/sfh/tests/test_diffburst.py
This PR changes the names of many private functions within diffburst.py, such as these:
1. `_age_weights_from_params` --> `_pureburst_age_weights_from_params`
2. `_age_weights_from_u_params` --> `_pureburst_age_weights_from_u_params`
and also changes the names of global parameters:
1. `DEFAULT_PARAMS` --> `DEFAULT_BURST_PARAMS`
2. `DEFAULT_U_PARAMS` --> `DEFAULT_BURST_U_PARAMS`
> Update diffburst.py with API-breaking changes to function and parameter names

- dsps/metallicity/tests/test_umzr.py
- dsps/metallicity/umzr.py
This PR brings in a new module umzr.py with a new implementation of the mass-metallicity-redshift scaling relation. The new module implements non-square bounds on the MZR parameters with the usual namedtuple syntax so that this scaling relation can be used in Diffsky fits. There are unit tests enforcing that the MZR has reasonable monotonic behavior for all points in the unbounded parameter space. And another unit test enforces that `mzr.py` and `mzr.py` have identical behavior for the current default model.
In future DSPS releases, `mzr.py` will be deprecated and eventually removed.
> Add new `umzr.py` module with unbounding behavior on MZR scaling relation

- dsps/tests/test_utils.py
Switch to scipy.integrate.trapezoid to avoid DeprecationWarning raised in unit testing. We have a cron workflow that treats warnings as errors. This PR resolves the recent failure of that cron.
This is also implemented in https://github.com/ArgonneCPAC/diffstar/pull/76.
> Resolve DeprecationWarning from using np.trapz in CI tests

- dsps/metallicity/diagnostics/plot_mzr.py
This PR brings in some additional target data into the MZR comparison plot. New version is like this:
> Update MZR diagnostic plot
